### PR TITLE
rename `VERSION_STRING` variable

### LINKED ISSUE #35: No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
To reproduce:
1. git clone
2. mkdir build && cd build
3. cmake ..

Error:
```
CMake Error at /usr/share/cmake-3.17/Modules/WriteBasicConfigVersionFile.cmake:43 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/CMakePackageConfigHelpers.cmake:225 (write_basic_config_version_file)
  /usr/lib64/cmake/GTSAMCMakeTools/GtsamMakeConfigFile.cmake:36 (write_basic_package_version_file)
  CMakeLists.txt:75 (GtsamMakeConfigFile)
```

System Info:
CMake: 3.17.1
GTSAM: 4.0.2
GCC: 9.3.0
OS: Arch Linux

### PR DESCRIPTION
**Pull request by acxz**
This is so that GtsamMakeConfigFile can find it, since it is case-sensitive.

Resolves #35 

Another way to resolve this would be to change https://github.com/gtrll/gpmp2/blob/master/CMakeLists.txt#L75

to `GtsamMakeConfigFile(gpmp2)`

But then other variables would need to be changed such as: `gpmp2_exports` to `GPMP2_exports`.
If you would like I go create a PR with that fix as well.

### CODE REVIEW

**Comment by acxz** [comment]
@mhmukadam can you take a look at this PR?

**Comment by acxz** [comment]
@mhmukadam or @dongjing3309 can one of you guys look at this PR? Thx!

**Comment by Leedk3** [comment]
Thank you. It helped me a lot!.
I changed the CMakeList.txt

```
.
.
.
#set(GPMP2_VERSION_STRING "${GPMP2_VERSION_MAJOR}.${GPMP2_VERSION_MINOR}.${GPMP2_VERSION_PATCH}")
set(gpmp2_VERSION_STRING "${GPMP2_VERSION_MAJOR}.${GPMP2_VERSION_MINOR}.${GPMP2_VERSION_PATCH}")
.
.
.
```

**Comment by Mr-Xia-6** [comment]
> 谢谢。这对我帮助很大！。
> 我更改了CMakeList.txt

How to chang the CMakeList.txt? THX

**Comment by acxz** [comment]
You can manually change the file or you can checkout the specific commit that has the fix.
git clone https://github.com/gtrll/gpmp2
cd gpmp2
git checkout 7052e91

Proceed with build instructions.

**Comment by Mr-Xia-6** [comment]
THX------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Akash&amp;nbsp;Patel&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月10日(星期四) 晚上8:35
收件人:&nbsp;&quot;gtrll/gpmp2&quot;<gpmp2@noreply.github.com&gt;;
抄送:&nbsp;&quot;Mr-Xia-6&quot;<1449470766@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [gtrll/gpmp2] rename `VERSION_STRING` variable (#34)

**Comment by WendyWang2019** [comment]
@Leedk3, Could you tell me how to change the CMakeList.txt in gpmp2 and which version of the gtsam used. Thank you.

**Comment by WendyWang2019** [comment]
@acxz 
git checkout 7052e91
error: pathspec '7052e91' did not match any file(s) known to git.
Please tell me where is the branch 7052e91. Thank you.

**Comment by acxz** [comment]
@WendyWang2019 mb I had a mistake in the repo to clone. Since this is a PR from my branch you need to make sure to clone `https://github.com/acxz/gpmp2` and then checkout the appropriate commit/branch.

**Comment by mhmukadam** [comment]
Hi @acxz, thanks for starting this PR. Can you pull in latest release 0.3.0 to verify if this problem still remains? Thanks.

**Comment by acxz** [comment]
This problem still remains as of 0.3.0 with the latest GTSAM release.

**Comment by mhmukadam** [comment]
With 0.3.0 release we have things working with gtsam `wrap-export`. Can you submit this PR to the `develop` branch instead where we will need to add more fixes before gpmp2 works with the latest gtsam release?

**Pull request closed without merging**
